// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "*.css?url" {
  const href: string;
  export default href;
}

interface ImportMetaEnv {
  readonly RPC_URL?: string;
  readonly VECTOR_PROGRAM?: string;
  readonly VERCEL_ENV?: "development" | "preview" | "production" | string;
  readonly BUN_PUBLIC_SOLANA_LOCALNET_RPC_URL?: string;
  readonly BUN_PUBLIC_SOLANA_DEVNET_RPC_URL?: string;
  readonly BUN_PUBLIC_SOLANA_TESTNET_RPC_URL?: string;
  readonly BUN_PUBLIC_SOLANA_MAINNET_RPC_URL?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
